{
  imports = [
    ./flameshot.nix
    ./hypridle.nix
    ./hyprland-qtutils.nix
    ./hyprshot.nix
    ./hyprlock.nix
    ./hyprpicker.nix
    ./hyprpanel.nix
    ./hyprpolkitagent.nix
    ./ksnip.nix
    ./pasystray.nix
    ./swaync
    ./swayosd.nix
    ./swww.nix
    ./variety.nix
    ./waybar
    ./wlogout
    ./wl-clipboard.nix
  ];
}
