{
  imports = [
    ./boot.nix
    ./flatpak.nix
    ./fonts.nix
    ./greetd.nix
    ./hardware.nix
    ./home-manager.nix
    ./network.nix
    ./nfs.nix
    ./nh.nix
    ./packages.nix
    ./power-management.nix
    ./printing.nix
    ./security.nix
    ./services.nix
    ./starfish.nix
    ./steam.nix
    ./stylix.nix
    ./syncthing.nix
    ./system.nix
    ./thunar.nix
    ./virtualisation.nix
    ./xserver.nix
  ];
}
